### PR TITLE
chore(environment): add environment specific config templates

### PR DESCRIPTION
**Pull request by vjgene**
add config-docker-template.json for develop, staging and testnet

### CODE REVIEW

**Review by rafaiovlabs — CHANGES_REQUESTED** [review]
For staging the rskendpoint should be: http://mkt-cache-01.aws-us-west-2.staging.marketplace.rifcomputing.net:4444 
And for testnet the endpoint should be: http://mkt-cache-01.aws-us-west-2.testnet.marketplace.rifcomputing.net:4444 
For mainnet can we have the template config-docker-template-mainnet.json ?  (this one with the default values for now)

**Comment by vjgene** [comment]
> For staging the rskendpoint should be: http://mkt-cache-01.aws-us-west-2.staging.marketplace.rifcomputing.net:4444
> And for testnet the endpoint should be: http://mkt-cache-01.aws-us-west-2.testnet.marketplace.rifcomputing.net:4444
> For mainnet can we have the template config-docker-template-mainnet.json ? (this one with the default values for now)

Thanks, these values are updated now. And config-docker-template-mainnet.json created

**Review by artem-brazhnikov — APPROVED** [review]
looks good, thanks

**Review by rafaiovlabs — APPROVED** [review]
LGTM

**Pull request merged**
