### PR TITLE
add circle ci

### PR DESCRIPTION
**Pull request by vjgene**
add circleci to project
steps to install rsk, mysql
run unit and integration tests

### CODE REVIEW

**Review by artem-brazhnikov — APPROVED** [review]
lgtm, waiting for @rafaiovlabs

**Review by rafaiovlabs — APPROVED** [review]
This CI configuration only deals with the RSK node interaction, but it seems to be lacking the rif-notifier CI itself, if this PR is for configuration + rsk node testing its ok to me.

**Comment by artem-brazhnikov** [comment]
> This CI configuration only deals with the RSK node interaction, but it seems to be lacking the rif-notifier CI itself, if this PR is for configuration + rsk node testing its ok to me.

Actually I think it would be good add it as well

**Review by artem-brazhnikov — CHANGES_REQUESTED** [review]
@vjgene check out rafaels comment plz

**Comment by vjgene** [comment]
> This CI configuration only deals with the RSK node interaction, but it seems to be lacking the rif-notifier CI itself, if this PR is for configuration + rsk node testing its ok to me.

I have added compile, build and test steps. Please let me know if any more steps to be added.

**Review by rafaiovlabs — APPROVED** [review]

**Review by artem-brazhnikov — APPROVED** [review]

**Pull request merged**
