### PR TITLE
feat(devops): add cd workflow

### PR DESCRIPTION
**Pull request by rafaiovlabs**
* adds cd workflow for dev, staging and testnet

### CODE REVIEW

**Comment by artem-brazhnikov** [comment]
@rafaiovlabs what is the status of this PR?

**Comment by rafaiovlabs** [comment]
> @rafaiovlabs what is the status of this PR?

The environments are now set up, so this PR can be merged @artem-brazhnikov  and then we can test for the dev env.

**Comment by artem-brazhnikov** [comment]
> > @rafaiovlabs what is the status of this PR?
> 
> The environments are now set up, so this PR can be merged @artem-brazhnikov and then we can test for the dev env.

1. Please assign me as a reviewer
2. The CD is failing, do you want to merge it in this state and then fix/

**Comment by rafaiovlabs** [comment]
> > > @rafaiovlabs what is the status of this PR?
> > 
> > 
> > The environments are now set up, so this PR can be merged @artem-brazhnikov and then we can test for the dev env.
> 
> 1. Please assign me as a reviewer
* Done
> 2. The CD is failing, do you want to merge it in this state and then fix/
* Yes the reason why it was failing was that the secrets were not created. anyways if after we merge it still fails i can fix.

**Review by artem-brazhnikov — APPROVED** [review]

**Comment by artem-brazhnikov** [comment]
@rafaiovlabs merged

**Pull request merged**
